<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260715200808 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE telemetry_record (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recorded_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, altitude INT DEFAULT NULL, speed SMALLINT DEFAULT NULL, ignition BOOLEAN DEFAULT NULL, movement BOOLEAN DEFAULT NULL, gsm_signal SMALLINT DEFAULT NULL, odometer BIGINT DEFAULT NULL, fuel_used BIGINT DEFAULT NULL, io JSONB DEFAULT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D95C8C10545317D1 ON telemetry_record (vehicle_id)');
        $this->addSql('CREATE INDEX idx_telemetry_vehicle_time ON telemetry_record (vehicle_id, recorded_at)');
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, imei VARCHAR(20) NOT NULL, plate VARCHAR(16) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B80E486B8179F8 ON vehicle (imei)');
        $this->addSql('ALTER TABLE telemetry_record ADD CONSTRAINT FK_D95C8C10545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE telemetry_record DROP CONSTRAINT FK_D95C8C10545317D1');
        $this->addSql('DROP TABLE telemetry_record');
        $this->addSql('DROP TABLE vehicle');
    }
}
